<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AnggotasTableSeeder extends Seeder{

  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
    {

      // 2016 (Cyber)

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160001'),
        'npm' => '140810160001',
        'nama' => 'Angga Kresnabayu',
        'jk' => 'L',
        'gol_dar' => 'A',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-08-20'),
        'tmpt_lhr' => 'Cirebon',
        'alamat' => 'Jl. Pangeran Purbaya, Blok Cibuk RT 04 RW 02
        Desa Purbawinangun, Kecamatan Plumbon. Kabupaten Cirebon, Jawa Barat',
        'no_hp' => '082226759976',
        'email' => 'angkres@gmail.com',
        'id_line' => 'angkres',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Kost Cemerlang, Dusun Ciseke RT 03 RW 03
        Desa Cikeruh, Kecamatan Jatinangor, Kabupaten Sumedang, Jawa Barat',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/01.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160002'),
        'npm' => '140810160002',
        'nama' => 'Tasya Amanda Adinegara',
        'jk' => 'P',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-11-15'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Jl. Farmakologi no.1 ',
        'no_hp' => '085723505577',
        'email' => 'achaadinegara@gmail.com',
        'id_line' => 'achaadinegara',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => '-',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/02.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160004'),
        'npm' => '140810160004',
        'nama' => 'Muhammad Ahsan Nurrijal',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-07-09'),
        'tmpt_lhr' => 'Sukabumi',
        'alamat' => 'Jl. Siliwangi Gg. Munajat 2 No.14 Kebonjati, Sukabumi',
        'no_hp' => '085864468331',
        'email' => 'schavelaar33@gmail.com',
        'id_line' => 'schavelaar33',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Griya Bandung Indah Blok E1 No.10 Buah Batu, Bandung',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/04.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160006'),
        'npm' => '140810160006',
        'nama' => 'Fajar Adiyansyah Rahiq',
        'jk' => 'L',
        'gol_dar' => 'B+',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-02-28'),
        'tmpt_lhr' => 'Baso',
        'alamat' => 'Koto Rapak, Jorong Baso, Kec.Baso, Kab.Agam, Sumatra Barat',
        'no_hp' => '085365405020',
        'email' => 'fajarrahiq@gmail.com',
        'id_line' => 'fajarrahiq',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Al-Amin 1, Ciseke Besar',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/06.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160007'),
        'npm' => '140810160007',
        'nama' => 'Fauzi Faruq Nabbani',
        'jk' => 'L',
        'gol_dar' => 'A',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1997-09-20'),
        'tmpt_lhr' => 'Tasikmalaya',
        'alamat' => 'Jl. Cipicung RT 06 RW 08 Kel. Tugujaya Kec. Cihideung, Kota Tasikmalaya',
        'no_hp' => '081216022936',
        'email' => 'fauzifaruqn@gmail.com',
        'id_line' => 'fauzifaruqn',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jalan Sukawening Pondok Hibar Buana Jatinangor',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/07.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160008'),
        'npm' => '140810160008',
        'nama' => 'Afifah Kho\'eriah',
        'jk' => 'P',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-01-03'),
        'tmpt_lhr' => 'Cirebon',
        'alamat' => 'Jalan Sabrang Permai No. 31 Blok B RT 003 RW 004 Stadion Bima, Cirebon, Jawa Barat',
        'no_hp' => '081947071822',
        'email' => 'Afifahkhoeriah@gmail.com',
        'id_line' => 'Afifahkhoeriah',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Infomasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Monica',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/08.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160009'),
        'npm' => '140810160009',
        'nama' => 'Raditya Prirahmadian',
        'jk' => 'L',
        'gol_dar' => 'B+',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-07-01'),
        'tmpt_lhr' => 'Kuningan',
        'alamat' => 'RT 07/ RW 04. Ling. Manis, Kel. Sukamulya, Kec. Cigugur, Kab. Kuningan',
        'no_hp' => '082295108710',
        'email' => 'radityaaap@gmail.com',
        'id_line' => 'radityaaap',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Infomasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondokan Ria Asri, Jalan Hegarmanah',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/09.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160010'),
        'npm' => '140810160010',
        'nama' => 'Reynaldi Noer Rizki',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-09-03'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Jl. Dukuh 5 RT/RW 010/005 no. 29 Kel. Dukuh Kec. Kramat Jati, Jakarta Timur',
        'no_hp' => '08979703291',
        'email' => 'reynaldinr@gmail.com',
        'id_line' => 'reynaldinr',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Ciseke Besar, Pondok Citra 86',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/10.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160011'),
        'npm' => '140810160011',
        'nama' => 'Muhammad Fariz',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-04-13'),
        'tmpt_lhr' => 'Padang',
        'alamat' => 'Jl. Dr. Arivai No. 89 Balai-Balai, Padang Panjang Sumatera Barat',
        'no_hp' => '085272656572',
        'email' => 'fasizzzz@gmail.com',
        'id_line' => 'Muhammadfariz13',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Infomasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Ciseke Kecil, Pondok Arghi',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/11.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160012'),
        'npm' => '140810160012',
        'nama' => 'Kevin A.A.J Waworuntu',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Kristen Protestan',
        'tgl_lhr' => Carbon::parse('1998-09-08'),
        'tmpt_lhr' => 'Bukittinggi',
        'alamat' => 'Pt. Subur Brothers Jalan Raya Bandung-Cirebon KM 73 bd, Cikalong-Tomo Kec. Tomo, Kab. Sumedang',
        'no_hp' => '087821898588',
        'email' => 'Kevinaajw@gmail.com',
        'id_line' => 'Kevinaajw',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Mahasiswa Caringin',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/12.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160013'),
        'npm' => '140810160013',
        'nama' => 'Muhammad Raihan Akbar',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1999-01-19'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Metland Tambun, Cluster Fontania Blok m2/18',
        'no_hp' => '089650097446',
        'email' => 'raihan_707@gmail.com',
        'id_line' => 'raihan_707',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Cisaladah, Kampung Cincin, Pondok Nirina',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/13.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160014'),
        'npm' => '140810160014',
        'nama' => 'Sachi Hongo',
        'jk' => 'L',
        'gol_dar' => 'A',
        'agama' => 'Buddha',
        'tgl_lhr' => Carbon::parse('1999-05-31'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => '-',
        'no_hp' => '085268425930',
        'email' => 'sachihongo99@gmail.com',
        'id_line' => 'sachihongo99',
        'angkatan' => '2016',
        'bidang_minat' => '', // TODO: isi bray
        'status_anggota' => 'Penuh',
        'kostan' => 'Cisaladah Ujung, Hergamanah, Jatinangor',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/14.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160015'),
        'npm' => '140810160015',
        'nama' => 'Dzakia Rayhana',
        'jk' => 'P',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('2000-01-22'),
        'tmpt_lhr' => 'Bekasi',
        'alamat' => 'Permata Regensi Blok E1 No.9, Bekasi',
        'no_hp' => '081285645242',
        'email' => 'dzkryhn@gmail.com',
        'id_line' => 'dzkryhn',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Wisma Nugraha, Desa Cikeruh',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/15.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160016'),
        'npm' => '140810160016',
        'nama' => 'Fikri Ikhsan',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-02-04'),
        'tmpt_lhr' => 'Padang',
        'alamat' => 'Jalan Sutan Syahrir, Gang Muhajirin, Kel. Mata Air, Kec. Padang Selatan, Kota Padang, Sumatera Barat',
        'no_hp' => '085263917794',
        'email' => 'f428@gmail.com',
        'id_line' => 'f428',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Abah Uni, Dusun Ciawi, Kel. Cikeruh Kec. Jatinangor, Kab. Sumedang, Jawa Barat',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/16.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160017'),
        'npm' => '140810160017',
        'nama' => 'Muhammad Yusuf Alfianto',
        'jk' => 'L',
        'gol_dar' => 'AB',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-07-30'),
        'tmpt_lhr' => 'Grobogan',
        'alamat' => 'Kp. Padurenan rt 01/05, Cibinong, Bogor',
        'no_hp' => '087711286270',
        'email' => 'yusuf_alfianto@gmail.com',
        'id_line' => 'yusuf_alfianto',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Trubus, gg.Haji nena. Jl.kolonel ahmad syams',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/17.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160018'),
        'npm' => '140810160018',
        'nama' => 'Erlangga Riyyan Nugraha',
        'jk' => 'L',
        'gol_dar' => 'B+',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1999-01-04'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Kp. Simpangwetan Ds. Sekarwangi RT.03/06 No 20 Kec. Soreang, Kab. Bandung, Jawa Barat',
        'no_hp' => '082127595155',
        'email' => 'rlangga_@gmail.com',
        'id_line' => 'rlangga_',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Komplek Puri Indah Blok A4 No.4 Desa Sayang',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/18.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160019'),
        'npm' => '140810160019',
        'nama' => 'Herizal Kurniawan',
        'jk' => 'L',
        'gol_dar' => 'A',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1997-12-15'),
        'tmpt_lhr' => 'Padang',
        'alamat' => 'Jln. Byduri V / 68 Perumnas Pagambiran, Kec. Lubuk Begalung, Kota Padang',
        'no_hp' => '085364088599',
        'email' => 'hrz_@gmail.com',
        'id_line' => 'hrz_',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jln. Ciseke Besar, Griya Wisuda',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/19.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160020'),
        'npm' => '140810160020',
        'nama' => 'Hasna Karimah',
        'jk' => 'P',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-09-15'),
        'tmpt_lhr' => 'Tangerang',
        'alamat' => 'Komp. Puspiptek blok IA/16 Serpong-Tangerang Selatan, Banten, Indonesia 14315',
        'no_hp' => '082298515256',
        'email' => 'karimahasnaa@gmail.com',
        'id_line' => 'karimahasnaa',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Kol. Achmad Syam Pondok Az Zahra',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/20.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160021'),
        'npm' => '140810160021',
        'nama' => 'Ilham Kusuma Aji',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-06-12'),
        'tmpt_lhr' => 'Garut',
        'alamat' => 'Jalan Majapahit 1 No.9 Taman Yunani R.21 Sentul City - Bogor',
        'no_hp' => '082182600612',
        'email' => 'ilhamkusumaaji@gmail.com',
        'id_line' => 'ilhamkusumaaji',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jalan Caringin No. 8a Jatinangor, Sumedang (Wisma Boulevard 2)',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/21.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160022'),
        'npm' => '140810160022',
        'nama' => 'Intan Pratiwi',
        'jk' => 'P',
        'gol_dar' => 'A',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-04-12'),
        'tmpt_lhr' => 'Simpang Batu Hampar',
        'alamat' => 'Bukittinggi, Sumatera Barat',
        'no_hp' => '082386018579',
        'email' => 'intaannpratiwii@gmail.com',
        'id_line' => 'intaannpratiwii',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Anggota Penuh',
        'kostan' => 'Ciseke Besar, Pondok Al Amin 3, RT 3 RW 3, Desa Cikeruh, Jatinangor, Kabupaten Sumedang, Jawa Barat',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/22.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160023'),
        'npm' => '140810160023',
        'nama' => 'Shaleh Husen Attamimi',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-10-09'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'JL. Sindang Kasih No. 30 Antapani Bandung',
        'no_hp' => '081395244474',
        'email' => 'shalehatta33@gmail.com',
        'id_line' => 'shalehatta33',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => '-',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/23.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160024'),
        'npm' => '140810160024',
        'nama' => 'Paquita Putri Ramadhani',
        'jk' => 'P',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-01-07'),
        'tmpt_lhr' => 'Cimahi',
        'alamat' => 'Jalan simpang no 67/B , Cimahi',
        'no_hp' => '087821826686',
        'email' => 'paquitaputri@gmail.com',
        'id_line' => 'paquitaputri',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Sakinah 2',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/24.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160025'),
        'npm' => '140810160025',
        'nama' => 'Teguh Riandi Pratama',
        'jk' => 'L',
        'gol_dar' => 'A',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-11-24'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Jl. Lengkong Tengah',
        'no_hp' => '081222682490',
        'email' => 'teguhrnd@gmail.com',
        'id_line' => 'teguhrnd',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Cikuda No. 21',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/25.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160026'),
        'npm' => '140810160026',
        'nama' => 'Syifa Fauziyah Nurul Islam',
        'jk' => 'P',
        'gol_dar' => 'AB',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1999-01-08'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Komp. Bumi Panyileukan P8 No. 11',
        'no_hp' => '087822135403',
        'email' => 'syifa0828@gmail.com',
        'id_line' => 'syifa0828',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => '-',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/26.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160027'),
        'npm' => '140810160027',
        'nama' => 'Muhammad Viqri Febryan ',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-02-07'),
        'tmpt_lhr' => 'Pekanbaru',
        'alamat' => 'Jl.Bakti Permai 8 No.110 Pekanbaru',
        'no_hp' => '082283109346',
        'email' => 'viqrifebryan@gmail.com',
        'id_line' => 'viqrifebryan',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl.Kolonel Ahmad Syam Kos Anggrek',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/27.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160028'),
        'npm' => '140810160028',
        'nama' => 'Muhammad Fahmi Irfananda',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-04-10'),
        'tmpt_lhr' => 'Pekalongan',
        'alamat' => 'Jl Jend A Yani 909 Bandung',
        'no_hp' => '087726244898',
        'email' => 'irfanan@gmail.com',
        'id_line' => 'irfanan',
        'angkatan' => '2016',
        'bidang_minat' => 'Jaringan Komputer',
        'status_anggota' => 'Penuh',
        'kostan' => '-',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/28.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160029'),
        'npm' => '140810160029',
        'nama' => 'Alif Naufal Hakim',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-09-02'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Jalan Cibatu Mulya 2 No. 2 Blok H Lama. Komplek Pasirjati, Cijambe, Ujungberung',
        'no_hp' => '08122810786',
        'email' => 'alifnaufalh@gmail.com',
        'id_line' => 'alifnaufalh',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Komplek Puri Indah Blok A4 No.4',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/29.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160030'),
        'npm' => '140810160030',
        'nama' => 'Adnan Januar Yunaz',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1999-01-04'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Jl. Graha Prima Baru, Blok T1 No. 31, Mangunjaya, Tambun, Bekasi',
        'no_hp' => '081219817187',
        'email' => 'balloonloverz@gmail.com',
        'id_line' => 'balloonloverz',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Ciseke Besar No. 31',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/30.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160031'),
        'npm' => '140810160031',
        'nama' => 'Muhammad Nur Anbiya Pohan',
        'jk' => 'L',
        'gol_dar' => 'A',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-11-05'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Jl. Delman Indah VI No.12 Tanah Kusir, Jakarta Selatan',
        'no_hp' => '081297884125',
        'email' => 'pohan@gmail.com',
        'id_line' => 'pohan',
        'angkatan' => '2016',
        'bidang_minat' => '',
        'status_anggota' => 'Penuh',
        'kostan' => 'Perumahan Puri Indah, Jatinangor, Jl. Sayang Blok, C6 No.16, Sumedang',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/31.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160032'),
        'npm' => '140810160032',
        'nama' => 'Mochamad Fa\'izin Ahsan',
        'jk' => 'L',
        'gol_dar' => 'A',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-09-11'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Perumaham Munjul Permai, Jl. Nakula 2 No. 3. RT 32, RW 10. Kelurahan Munjul. Purwakarta',
        'no_hp' => '087778628883',
        'email' => 'faizin11@gmail.com',
        'id_line' => 'faizin11',
        'angkatan' => '2016',
        'bidang_minat' => 'Jaringan Komputer',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jalan GKPN No.34 Cibeusi Jatinangor',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/32.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160033'),
        'npm' => '140810160033',
        'nama' => 'Muhammad Naufal Monoarfa',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-11-16'),
        'tmpt_lhr' => 'Depok',
        'alamat' => 'Jl. Cendrawasih 3 No. 211 RT 01/08 Depok Jaya, Pancoranmas, Kota Depok, Jawa Barat',
        'no_hp' => '085718803408',
        'email' => 'mrmonoarfa@gmail.com',
        'id_line' => 'mrmonoarfa',
        'angkatan' => '2016',
        'bidang_minat' => 'Jaringan Komputer',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Hegarmanah No.12 RT 02/03 Jarinangor, Sumedang',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/33.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160035'),
        'npm' => '140810160035',
        'nama' => 'Santo Joosten Malau',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Katolik',
        'tgl_lhr' => Carbon::parse('1998-10-03'),
        'tmpt_lhr' => 'Medan',
        'alamat' => 'Jl Datuk Kabu Psr III Gg Rahmat No 10 Medan',
        'no_hp' => '082167492312',
        'email' => 'santojoosten@gmail.com',
        'id_line' => 'santojoosten',
        'angkatan' => '2016',
        'bidang_minat' => 'Jaringan Komputer',
        'status_anggota' => 'Penuh',
        'kostan' => 'Komplek Puri Indah Jatinangor  Blok A4 No 4 Jatinagor',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/35.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160036'),
        'npm' => '140810160036',
        'nama' => 'Malik Zulfikar Gantina',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-11-11'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Komp. Permata Hijau F-07, RT 02 RW 19. Kecamatan Rancaekek, Kab. Bandung. Indonesia.',
        'no_hp' => '081221471298',
        'email' => 'zulfikarg@gmail.com',
        'id_line' => 'zulfikarg',
        'angkatan' => '2016',
        'bidang_minat' => 'Jaringan Komputer',
        'status_anggota' => 'Penuh',
        'kostan' => '-',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/36.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160037'),
        'npm' => '140810160037',
        'nama' => 'Rafidghadah Damarta',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-08-26'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Jl. Guntur Sari I No. 25, Buah batu, Bandung',
        'no_hp' => '081574142222',
        'email' => 'rafidghadah@gmail.com',
        'id_line' => 'rafidghadah',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Raya Jatinangor No. 150',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/37.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160038'),
        'npm' => '140810160038',
        'nama' => 'Satrio Sadrakh Allesandro',
        'jk' => 'L',
        'gol_dar' => 'AB',
        'agama' => 'Protestan',
        'tgl_lhr' => Carbon::parse('1998-08-16'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Jl. PSM Dalam 1 No. 95',
        'no_hp' => '89613603028',
        'email' => 'satrio_88io@gmail.com',
        'id_line' => 'satrio_88io',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => '',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/38.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160039'),
        'npm' => '140810160039',
        'nama' => 'Yaumi Hadi Maulana',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1999-01-08'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Jl. Galaksi 4 No. 37, Margahayu Raya, Bandung',
        'no_hp' => '081224085197',
        'email' => 'yaumi08@gmail.com',
        'id_line' => 'yaumi08',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Nataka residence',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/39.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160040'),
        'npm' => '140810160040',
        'nama' => 'Muhammad Jordiansyah',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1997-09-18'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Citra Raya Blok I 16 no 2',
        'no_hp' => '081297532902',
        'email' => 'm.jordi@gmail.com',
        'id_line' => 'm.jordi',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Kost H. Pepen, Ciseke Besar',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/40.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160042'),
        'npm' => '140810160042',
        'nama' => 'Aditya Rizky Fadillah',
        'jk' => 'L',
        'gol_dar' => 'AB',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1997-12-18'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Komp. Pilar Biru Jl. Pilar Biru Raya No .6 RT 01/RW 12 Ds. Cibiru Hilir Kec. Cileunyi Kab. Bandung',
        'no_hp' => '082318585855',
        'email' => 'adityaarizkyf@gmail.com',
        'id_line' => 'adityaarizkyf',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => '-',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/42.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160043'),
        'npm' => '140810160043',
        'nama' => 'Fidriyanto Rizkillah',
        'jk' => 'L',
        'gol_dar' => 'A',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-10-24'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Jl. Pondok Kopi 2C, Blok C7 Nomor 5, Jakarta Timur, DKI Jakarta',
        'no_hp' => '081293168889',
        'email' => 'rezyfr@gmail.com',
        'id_line' => 'rezyfr',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Caringin No. 23, Jatinangor',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/43.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160044'),
        'npm' => '140810160044',
        'nama' => 'Bening Kusumahati',
        'jk' => 'P',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-04-03'),
        'tmpt_lhr' => 'Magetan',
        'alamat' => 'Jalan Batununggal Permai II No. 38 Bandung',
        'no_hp' => '081322084150',
        'email' => 'beningk@gmail.com',
        'id_line' => 'beningk',
        'angkatan' => '2016',
        'bidang_minat' => 'Jaringan Komputer',
        'status_anggota' => 'Penuh',
        'kostan' => '',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/44.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160045'),
        'npm' => '140810160045',
        'nama' => 'Januar Lazuardi',
        'jk' => 'L',
        'gol_dar' => 'A',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1999-01-27'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Jl. Sampora Gg. Pak Adin no.5 RT 01 RW 16 Bandung 40227',
        'no_hp' => '082240763483',
        'email' => 'januarlazuardi@gmail.com',
        'id_line' => 'januarlazuardi',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Griya Jatinangor 2 Jl. Palem 9 blok A15 no. 3',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/45.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160046'),
        'npm' => '140810160046',
        'nama' => 'Hilya Tsaniya',
        'jk' => 'P',
        'gol_dar' => 'AB',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1999-07-13'),
        'tmpt_lhr' => 'Padang',
        'alamat' => 'Gang Utama Perumahan Permata Dadok Tunggul Itam, Padang',
        'no_hp' => '083180557693',
        'email' => 'hilya_tsaniya@gmail.com',
        'id_line' => 'hilya_tsaniya',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Lestari, Ciseke Besar',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/46.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160047'),
        'npm' => '140810160047',
        'nama' => 'Syafira Fitra Annisa',
        'jk' => 'P',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1999-01-27'),
        'tmpt_lhr' => 'Pekanbaru',
        'alamat' => 'Jl. Rambutan 2 Perum. Telaga Biru Blok G No. 2, Pekanbaru',
        'no_hp' => '085271937646',
        'email' => 'syafitra99@gmail.com',
        'id_line' => 'syafitra99',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Kos Fenori, Jl. Ciseke Besar No. 256',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/47.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160048'),
        'npm' => '140810160048',
        'nama' => 'Baby Cattleya Gustina Permatagama',
        'jk' => 'P',
        'gol_dar' => 'A',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-11-18'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Perumahan Cimareme Indah Blok A2-20, Padalarang, Bandung Barat',
        'no_hp' => '083821011879',
        'email' => 'becgp@gmail.com',
        'id_line' => 'becgp',
        'angkatan' => '2016',
        'bidang_minat' => 'Jaringan Komputer',
        'status_anggota' => 'Penuh',
        'kostan' => '',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/48.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160049'),
        'npm' => '140810160049',
        'nama' => 'Adryan Luthfi Faiz',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-05-17'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Komp. Dewa Kembar No.173/A RT 09/01 Jakarta',
        'no_hp' => '08987817332',
        'email' => 'iyonadryanlf@gmail.com',
        'id_line' => 'iyonadryanlf',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok bahagia Jl.kolonel syam, Cikeruh 01/05, Jatinangor, Sumedang, Jawa Barat. 45363',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/49.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160050'),
        'npm' => '140810160050',
        'nama' => 'Balar Nyalasivaa',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-10-19'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Jl. Subang 14 No. 39 Antapani Bandung',
        'no_hp' => '081932028049',
        'email' => 'albaryaaln@gmail.com',
        'id_line' => 'albaryaaln',
        'angkatan' => '2016',
        'bidang_minat' => '',
        'status_anggota' => 'Penuh',
        'kostan' => '',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/50.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160051'),
        'npm' => '140810160051',
        'nama' => 'Zaenal Muttaqien',
        'jk' => 'L',
        'gol_dar' => 'AB',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-07-17'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Bandung, Jalan Leuwipanjang Gg. Abaharga no 93/200A RT/RW 04/08',
        'no_hp' => '081221587732',
        'email' => 'muttaqienzae@gmail.com',
        'id_line' => 'muttaqienzae',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Komplek Puri Indah Blok A4 No.4',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/51.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160053'),
        'npm' => '140810160053',
        'nama' => 'Vega Savera Yuana',
        'jk' => 'P',
        'gol_dar' => 'AB',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-02-09'),
        'tmpt_lhr' => 'Banda Aceh',
        'alamat' => 'Lamprit, Banda Aceh',
        'no_hp' => '085262456235',
        'email' => 'vegayuana@gmail.com',
        'id_line' => 'vegayuana',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Askalena, Kampung Geulis, Jatinangor',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/53.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160054'),
        'npm' => '140810160054',
        'nama' => 'Ibnu Ahsani',
        'jk' => 'L',
        'gol_dar' => 'B-',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1997-05-17'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Jl. Lestari No. 46 RT 009/03, Kalisari, Pasar Rebo, Jakarta Timur',
        'no_hp' => '085946260642',
        'email' => 'ibnu.muhari@gmail.com',
        'id_line' => 'ibnu.ahsani',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Sukawening',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/54.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160055'),
        'npm' => '140810160055',
        'nama' => 'Muhammad Rifqy Aulia Akbar',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-02-28'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Jl. Purbasari 1 No.46, RT 02/05, sangkuriang, cipageran, cimahi utara',
        'no_hp' => '085864196830',
        'email' => 'seth7x@gmail.com',
        'id_line' => 'seth7x',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Raya jatinangor no.138',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/55.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160056'),
        'npm' => '140810160056',
        'nama' => 'Muhammad Ihza Triyanto',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-04-28'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Saka Kencana, Buperta, RT 001/05, Kel. Pondok Ranggon, Kec. Cipayung, Jakarta Timur',
        'no_hp' => '081212862858',
        'email' => 'ihzariyanto@gmail.com',
        'id_line' => 'ihzariyanto',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Galumpit, Cileunyi Wetan, Cileunyi, Kab. Bandung',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/56.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160057'),
        'npm' => '140810160057',
        'nama' => 'Shofiyyah Nadhiroh',
        'jk' => 'P',
        'gol_dar' => 'B+',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1999-11-28'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Jl. Masjid Nurul Huda RT/RW 03/06 no. 136, Tanjung Barat, Jagakarsa, Jakarta Selatan',
        'no_hp' => '082299285050',
        'email' => 'Shofiyyahnadhiroh2@gmail.com',
        'id_line' => 'Shofiyyahnadhiroh2',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Griya Murti, Cikuda',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/57.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160058'),
        'npm' => '140810160058',
        'nama' => 'Daffa Alief Rana',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-08-26'),
        'tmpt_lhr' => 'Lhokseumawe ',
        'alamat' => 'Jl. Blang Cot,  Desa Punie, Kecamatan Darul Imarah, Mata Ie, Aceh Besar, Aceh',
        'no_hp' => '082165120020',
        'email' => 'daffaliefr@gmail.com',
        'id_line' => 'daffaliefr',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl Cikuda-Cileles ,rw 11, Neglasari, Cikuda, Hegarmanah, Jatinangor, Jawa Barat',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/58.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160060'),
        'npm' => '140810160060',
        'nama' => 'Beryl Cleary Hermanto',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Katolik',
        'tgl_lhr' => Carbon::parse('1999-12-26'),
        'tmpt_lhr' => 'Cimahi',
        'alamat' => 'Jl. K. H. Hasan Arief No. 337, Garut',
        'no_hp' => '08994438370',
        'email' => 'real1vis@gmail.com',
        'id_line' => 'real1vis',
        'angkatan' => '2016',
        'bidang_minat' => '',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Natasha Ciseke Kecil, Cikeruh, Jatinangor, Sumedang',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/60.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160061'),
        'npm' => '140810160061',
        'nama' => 'Eko Fajar Putra',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1995-11-27'),
        'tmpt_lhr' => 'Malang',
        'alamat' => 'Jalan Karya Bhakti VI No 8 RT 03 RW 11 Kelurahan Cigugur Tengah Kecamatan Cimahi Tengah Kota Cimahi 40522',
        'no_hp' => '08112252627',
        'email' => 'fajarputrae@gmail.com',
        'id_line' => 'fajarputrae',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => 'Puri Indah Jatinangor Estate blok A4 No. 4 Jl. Sayang Jatinangor Bandung - Sumedang',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/61.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160062'),
        'npm' => '140810160062',
        'nama' => 'Muhammad Islam Taufikurahman',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-06-23'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Jl. Golf Barat XVI No. 11, Arcamanik',
        'no_hp' => '082214023544',
        'email' => 'islam.taufikurahman@gmail.com',
        'id_line' => 'muham_istau',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => '',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/62.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160063'),
        'npm' => '140810160063',
        'nama' => 'Gitra Elang Khanti',
        'jk' => 'L',
        'gol_dar' => 'AB',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-04-30'),
        'tmpt_lhr' => 'Padang',
        'alamat' => 'Jalan Bunda III no. 3 Padang',
        'no_hp' => '081372797268',
        'email' => 'elangkhanti@gmail.com',
        'id_line' => 'elangkhanti',
        'angkatan' => '2016',
        'bidang_minat' => '',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Salsabila (depan IPDN)',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/63.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160064'),
        'npm' => '140810160064',
        'nama' => 'Bariq Mbani',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1997-08-23'),
        'tmpt_lhr' => 'Cimahi',
        'alamat' => 'Jl. Mendut Raya M.70 RT02 RW18 Pharmindo, Cimahi Selatan 40534',
        'no_hp' => '083829357213',
        'email' => 'bariqmbani@gmail.com',
        'id_line' => 'bariqmbani',
        'angkatan' => '2016',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Penuh',
        'kostan' => '',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/64.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160065'),
        'npm' => '140810160065',
        'nama' => 'Patricia Joanne',
        'jk' => 'P',
        'gol_dar' => 'O',
        'agama' => 'Protestan',
        'tgl_lhr' => Carbon::parse('1999-06-24'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Jl. Tanah Manisan no. 62 RT 13/11 Cawang Cipinang Cempedak Kec. Jatinegara Jakarta Timur 13340',
        'no_hp' => '081932698624',
        'email' => 'realicejoanne@gmail.com',
        'id_line' => 'realicejoanne',
        'angkatan' => '2016',
        'bidang_minat' => 'Artificial Intelligence',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Lapang Bola RT 03/05 Desa Cikeruh Kec. Jatinangor Kab. Sumedang',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/65.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810160067'),
        'npm' => '140810160067',
        'nama' => 'Muhammad Rafif Abieza Pradhana',
        'jk' => 'L',
        'gol_dar' => 'B',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-12-12'),
        'tmpt_lhr' => 'Bandar Lampung',
        'alamat' => 'Jalan sultan agung gg raden saleh no 24a ',
        'no_hp' => '082180140027',
        'email' => 'Abiezapradhana@gmail.com',
        'id_line' => 'Abiezapradhana',
        'angkatan' => '2016',
        'bidang_minat' => '',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jalan raya jatinangor no142 cikeruh',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/67.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810167001'),
        'npm' => '140810167001',
        'nama' => 'Melati S Abisay',
        'jk' => 'P',
        'gol_dar' => 'B',
        'agama' => 'Protestan',
        'tgl_lhr' => Carbon::parse('1997-05-12'),
        'tmpt_lhr' => 'Waropen Papua',
        'alamat' => 'Sp 5 Jalur 4 Timur',
        'no_hp' => '081248349861',
        'email' => 'tesuto@gmail.com',
        'id_line' => 'tesuto',
        'angkatan' => '2016',
        'bidang_minat' => '',
        'status_anggota' => 'Penuh',
        'kostan' => '81248349861',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2016/7001.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810170065'),
        'npm' => '140810170065',
        'nama' => 'Yoga Prambudi Sunaryudanto Putro',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1997-07-04'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Komp. Vijayakusumah B4. No 1',
        'no_hp' => '082214159089',
        'email' => 'sabers1@gmail.com',
        'id_line' => 'sabers1',
        'angkatan' => '2017',
        'bidang_minat' => '-',
        'status_anggota' => 'Penuh',
        'kostan' => '-',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2017/65.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810120001'),
        'npm' => '140810120001',
        'nama' => 'Jordy Saragih',
        'jk' => 'L',
        'gol_dar' => '-',
        'agama' => 'Kristen',
        'tgl_lhr' => Carbon::parse('1993-04-21'),
        'tmpt_lhr' => 'Jakarta',
        'alamat' => 'Jl. Sutera Cemara I no. 16 Perumahan Alam Sutera. Serpong Utara. Tangerang Selatan. ',
        'no_hp' => '087888688078',
        'email' => 'jordysaragih@gmail.com',
        'id_line' => 'jordysaragih',
        'angkatan' => '2012',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Kehormatan',
        'kostan' => '-',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2012/01.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810130001'),
        'npm' => '140810130001',
        'nama' => 'Carina Sunny Budiono Putri',
        'jk' => 'P',
        'gol_dar' => '-',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1995-03-21'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Dsn Manis Rt. 11 Rw. 04 No.22 Kecamatan Darma Kab. Kuningan 45562',
        'no_hp' => '089652243169',
        'email' => 'carinasunnybp@gmail.com',
        'id_line' => 'carinasunnybp',
        'angkatan' => '2013',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Kehormatan',
        'kostan' => '-',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2013/01.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810140001'),
        'npm' => '140810140001',
        'nama' => 'Delia Hayatul Millah',
        'jk' => 'P',
        'gol_dar' => 'AB',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1996-12-18'),
        'tmpt_lhr' => 'Purwakarta',
        'alamat' => 'Tegal Junti RT 01/04 No. 22 Kelurahan Tegal Munjul Kecamatan Purwakarta 41116 , Jawa Barat',
        'no_hp' => '089527303513',
        'email' => 'deliahm@gmail.com',
        'id_line' => 'deliahm',
        'angkatan' => '2014',
        'bidang_minat' => 'Sistem Informasi',
        'status_anggota' => 'Kehormatan',
        'kostan' => '-',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2014/01.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810150001'),
        'npm' => '140810150001',
        'nama' => 'Muhammad Gilang Akbar H',
        'jk' => 'L',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1998-02-04'),
        'tmpt_lhr' => 'Cianjur',
        'alamat' => 'Jl. Raya Cipanas KM. 4 Kp. Cangklek Ds. Sukamanah Rt 01/01 Kec. Cugenang Cianjur',
        'no_hp' => '085846357529',
        'email' => 'hikmawangilang@gmail.com',
        'id_line' => 'hikmawangilang',
        'angkatan' => '2015',
        'bidang_minat' => 'Jaringan Komputer',
        'status_anggota' => 'Penuh',
        'kostan' => 'Jl. Raya Jatinangor Komplek Janati Park Cluster 2 Blok G No. 8 Sumedang, Jawa Barat',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2015/01.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810170001'),
        'npm' => '140810170001',
        'nama' => 'Faradilla Azranur',
        'jk' => 'P',
        'gol_dar' => 'O',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('1999-08-07'),
        'tmpt_lhr' => 'Bandung',
        'alamat' => 'Komp. Margahayu No.416 Kel. Babakan Jawa, Kab. Majalengka',
        'no_hp' => '081340312615',
        'email' => 'fardil7@gmail.com',
        'id_line' => 'fardil7',
        'angkatan' => '2017',
        'bidang_minat' => '-',
        'status_anggota' => 'Penuh',
        'kostan' => 'Pondok Sakura, Cikeruh',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2017/01.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);

      DB::table('anggotas')->insert([
        'password' => app('hash')->make('140810180001'),
        'npm' => '140810180001',
        'nama' => 'Sheila Azhar Almufarida',
        'jk' => 'P',
        'gol_dar' => 'A+',
        'agama' => 'Islam',
        'tgl_lhr' => Carbon::parse('2000-04-18'),
        'tmpt_lhr' => 'Kuningan',
        'alamat' => 'Ds. Kertawangunan No.1 RT. 04 RW. 03 Kec. Sindangagung Kuningan Jawa Barat',
        'no_hp' => '081223728134',
        'email' => 'sheilaazhara@gmail.com',
        'id_line' => 'sheilaazhara',
        'angkatan' => '2018',
        'bidang_minat' => '-',
        'status_anggota' => 'Penuh',
        'kostan' => 'Kost Putri Handayani Jl. Raya Jatinangor 193',
        'url_foto' => 'http://hda.himatif.org/assets/foto/2018/01.jpg',
        'api_token' => str_random(10),
        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      ]);
    }
}
